version: "3.7"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - remix:/var/lib/postgresql/data

volumes:
  remix:
